# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11aab99e3e6dbeb655fffbca6fe9d6a2165baaf4a9d8a614e1cf4105411910ee9b9bc375942b7634b6dee4568cbdb54d3c0da6994f1e0ab4ea00edef80a0008e

test:
  secret_key_base: 33b76145297af7a400d1bea8ff19047d9e03ba0123b48729d09636051987dc95f9ff9a0bf360d696c43f08e6c99d0f567b2c7656dbd2611ef8493b126f114c13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
